// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX4cF0Ati-_tjUdb1d8el3PFXEjrdxleg',
    appId: '1:582777489362:web:33d987851c9f51a7146a0b',
    messagingSenderId: '582777489362',
    projectId: 'taxiapp-5c2a5',
    authDomain: 'taxiapp-5c2a5.firebaseapp.com',
    storageBucket: 'taxiapp-5c2a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA17PSO8IvmEJqGX3yUY2sUb8Ujy6g6JBk',
    appId: '1:582777489362:android:9d197e4f7bc52501146a0b',
    messagingSenderId: '582777489362',
    projectId: 'taxiapp-5c2a5',
    storageBucket: 'taxiapp-5c2a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiN3URrhvyXqH6PCDLtwkEnbBeE2IJUEA',
    appId: '1:582777489362:ios:a42018cfff516987146a0b',
    messagingSenderId: '582777489362',
    projectId: 'taxiapp-5c2a5',
    storageBucket: 'taxiapp-5c2a5.appspot.com',
    iosClientId: '582777489362-d7frhpmd2dijg9lmdks672ciprj3pede.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxiapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiN3URrhvyXqH6PCDLtwkEnbBeE2IJUEA',
    appId: '1:582777489362:ios:a42018cfff516987146a0b',
    messagingSenderId: '582777489362',
    projectId: 'taxiapp-5c2a5',
    storageBucket: 'taxiapp-5c2a5.appspot.com',
    iosClientId: '582777489362-d7frhpmd2dijg9lmdks672ciprj3pede.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxiapp',
  );
}
